module.exports = {
    alps: require('./alps'),
    button: require('./button'),
    button_YD3414: require('./button_YD3414'),
    choc: require('./choc'),
    chocmini: require('./chocmini'),
    diode: require('./diode'),
    jstph: require('./jstph'),
    jumper: require('./jumper'),
    mx: require('./mx'),
    mounting_hole: require('./mounting_hole'),
    oled: require('./oled'),
    omron: require('./omron'),
    pad: require('./pad'),
    promicro: require('./promicro'),
    rgb: require('./rgb'),
    rotary: require('./rotary'),
    scrollwheel: require('./scrollwheel'),
    slider: require('./slider'),
    switcher_MSK12C02: require('./switcher_MSK12C02'),
    trrs: require('./trrs'),
    via: require('./via'),
}